---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 4440, host: 4440}]

provisioner:
  name: chef_solo
  attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      balanced-apt:
        allow_unstable: true
      precog:
        notice_addrs:
        - test+precog@balancedpayments.com
      precog:
        alert_addrs:
        - test+precog@balancedpayments.com

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - recipe[role-balanced-commander::integration]
