---
kitchen:
  log_level: debug

driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 4440, host: 4444}]

provisioner:
  name: chef_solo
  attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      balanced-apt:
        allow_unstable: true
      precog:
        notice_addrs:
        - test+precog@balancedpayments.com
      precog:
        alert_addrs:
        - test+precog@balancedpayments.com
      balanced:
        jobs:
          failure_recipient: fail@vandelay.io

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - recipe[role-balanced-commander::dev]
    attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      sentry:
        enabled: false
      rundeck:
        proxy:
          default: false

  - name: live
    run_list:
    - recipe[awscli::default]
    - recipe[role-balanced-commander::live]
    attributes:
      solo_rb:
        config:
          log_level: ":debug"
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      sentry:
        enabled: false
      rundeck:
        proxy:
          default: false
      postgres:
        integration:
          slave: <%= ENV['DB_PROD_INTEGRATION'] %>
        live:
          slave: <%= ENV['DB_PROD_LIVE'] %>
